# Multi-stage build para Next.js
FROM node:18-alpine AS base

# Instalar dependencias solo cuando sea necesario
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copiar archivos de dependencias
COPY package.json package-lock.json* ./
RUN npm ci

# Build de la aplicación
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Variables de entorno para build
ARG NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyAQ0zuspsoBEQ54rCDGTKbAeHM96DVl3ZU"
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="owl-coach.firebaseapp.com"
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID="owl-coach"
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="owl-coach.firebasestorage.app"
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="831473832501"
ARG NEXT_PUBLIC_FIREBASE_APP_ID="1:831473832501:web:2e88bf60073fe84947177c"
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-HBKC82DJ4Q"
ENV NEXT_TELEMETRY_DISABLED 1
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

# Build Next.js
RUN npm run build

# Imagen de producción
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
ENV PORT 8080
ENV HOSTNAME "0.0.0.0"
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Variables de entorno runtime para Firebase Admin (configurar en Cloud Run)
ENV FIREBASE_PROJECT_ID ""
ENV FIREBASE_PRIVATE_KEY ""
ENV FIREBASE_CLIENT_EMAIL ""

# Variables públicas de Firebase en runtime
ARG NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyAQ0zuspsoBEQ54rCDGTKbAeHM96DVl3ZU"
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="owl-coach.firebaseapp.com"
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID="owl-coach"
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="owl-coach.firebasestorage.app"
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="831473832501"
ARG NEXT_PUBLIC_FIREBASE_APP_ID="1:831473832501:web:2e88bf60073fe84947177c"
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-HBKC82DJ4Q"
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

# Crear usuario no-root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copiar archivos necesarios
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
	CMD wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1

# Ejecuta Next.js en modo producción
CMD ["npx", "next", "start"]
